### ISSUE TITLE
Error when run cartoonize.py

### ISSUE THREAD

**Issue by MNCTTY** [mnicnc404/CartoonGan-tensorflow#21]
Hello! I tried to run simply cartoonize.py with all default arguments and faced this error:

```
Traceback (most recent call last):
  File "cartoonize.py", line 371, in <module>
    main()
  File "cartoonize.py", line 355, in main
    output_image = post_processing(transformed_image, style=style)
  File "cartoonize.py", line 110, in post_processing
    transformed_image = transformed_image.numpy()
AttributeError: 'Tensor' object has no attribute 'numpy'
```

What it can be?

**Comment by abelghazinyan** [comment]
change to np.array(transformed_image)

**Comment by mumtozvalijonov** [comment]
@MNCTTY That's a TF version issue

**Comment by mnicnc404** [comment]
It seems that you're using tf 1.x. Please follow the instructions of environment settings introduced in README.md to install the correct version of TensorFlow for this repo.
