### ISSUE TITLE
Error running inference_with_ckpt.py

### ISSUE THREAD

**Issue by idevji1** [mnicnc404/CartoonGan-tensorflow#25]
**Following error is encountered when running inference_with_ckpt.py :**
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
[2019-10-27 06:30:31] [inference] [INFO] generating image from images/cartoonize-script-demo.jpg
Traceback (most recent call last):
  File "inference_with_ckpt.py", line 52, in <module>
    main(args.m_path, args.img_path, args.out_dir, args.light)
  File "inference_with_ckpt.py", line 23, in main
    g.load_weights(tf.train.latest_checkpoint(m_path))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py", line 1481, in load_weights
    status.assert_nontrivial_match()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py", line 622, in assert_nontrivial_match
    "checkpointed value: %s") % (list(unused_python_objects),))
AssertionError: Nothing except the root object matched a checkpointed value. Typically this means that the checkpoint does not match the Python program. The following objects have no matching checkpointed value: [<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd01400>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd40400>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd86400>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd37208>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd4fe10>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd81c18>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd67a20>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd37828>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd28630>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd13630>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd1f438>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd81438>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd6d438>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd18240>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd01e48>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd13e48>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd57e48>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd4fc50>, <layers.ConvBlock object at 0x7f470cd6dc50>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd1fa58>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd57860>, <layers.FlatConv object at 0x7f471cfda668>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd01278>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd40278>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd67278>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd37e80>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd40080>, <layers.ResBlock object at 0x7f470cd18080>, <layers.ResBlock object at 0x7f470cd67080>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd13c88>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470ccd9a90>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd81a90>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd40a90>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd01a90>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd5e898>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd576a0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd866a0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd284a8>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd4f4a8>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd282b0>, <layers.ResBlock object at 0x7f470cd4f2b0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd480b8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470ccd90b8>, <layers.UpSampleConv object at 0x7f470cd77eb8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd770b8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd57cc0>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd28cc0>, <tensorflow.python.keras.layers.core.Activation object at 0x7f470cd86cc0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd48ac8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd018d0>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd408d0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd376d8>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470ccd96d8>, <layers.ResBlock object at 0x7f470cd374e0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd812e8>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd862e8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd302e8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd6def0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd40ef0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd30cf8>, <layers.ConvBlock object at 0x7f470cd01cf8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd28b00>, <layers.UpSampleConv object at 0x7f470cd6d908>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd1f908>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd6d710>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd5e710>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd77710>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470ccd9518>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd18518>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd5e518>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd67f28>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd5ef28>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd18f28>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd4ff28>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd86b38>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd48940>, <layers.ConvBlock object at 0x7f470ccd9940>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd48748>, <layers.ResBlock object at 0x7f470cd1f748>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd67550>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd5e358>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd13160>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd30160>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd5ed68>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470ccd9d68>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd30b70>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd57b70>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd30978>, <layers.ResBlock object at 0x7f470cd57978>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd4f780>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd48588>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd1f5f8>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd77588>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd4f5f8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470ccf3390>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd18390>, <layers.ConvBlock object at 0x7f470cd81198>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd01f98>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd48f98>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd4f198>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd1ff98>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd67da0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd18da0>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd77da0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd40da0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd6dda0>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd18ba8>, <layers.ResBlock object at 0x7f470cd40ba8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd379b0>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd307b8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd137b8>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd815c0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470cd673c8>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd373c8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd81fd0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470cd28fd0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd571d0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f470ccf3dd8>, <layers.ResBlock object at 0x7f470cd28dd8>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd77be0>, <tensorflow.python.keras.layers.convolutional.ZeroPadding2D object at 0x7f470ccd9be0>, <tensorflow.python.keras.layers.convolutional.Conv2D object at 0x7f470cd1fbe0>, <tensorflow.python.keras.layers.advanced_activations.ReLU object at 0x7f470cd67be0>, <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x7f470cd189e8>, <tensorflow.python.keras.layers.merge.Add object at 0x7f470cd6d5f8>]

**Additional info:**
- Trained using --light (Supplying or not supplying --light generates same error) 
- Files in dir provided to m_path : checkpoint  generator-100.data-00000-of-00001  generator-100.index
- Trained and executed on Google Colab

**Comment by Nantouren** [comment]
hello,
did you overcome this problem?

**Comment by mnicnc404** [comment]
Hi,

It seems that you are not using the suggested environment management method (conda) we provided. Since we're no longer maintaining this repo, to reproduce the result, please make sure that you're using conda and 100% following the instructions.

If you're using colab and don't know how to use conda on colab, there are several resources that can help you do so, e.g., [https://stackoverflow.com/questions/53000670](https://stackoverflow.com/questions/53000670).

**Comment by pradyumnjain** [comment]
did anyone found the solution to this?
