### ISSUE TITLE
Insufficient graphics card memory

### ISSUE THREAD

**Issue by iwanttobeabigone** [mnicnc404/CartoonGan-tensorflow#34]
2G graphics card can't train, even if batch_size is set to 1. Can only complete pre-training.

**Comment by mnicnc404** [comment]
The default `input_size` is 256. You can try setting `input_size` to a smaller number like 128:

```
python --input_size=128 ...
```

Or, you can set base_filters (default 64) and d_base_filters (default 32) to a smaller number by modifying `train.py`.
