### ISSUE TITLE
Is there a way to use this in Android app?

### ISSUE THREAD

**Issue by abanoub-hanna** [mnicnc404/CartoonGan-tensorflow#36]
Hi,

Is there any tutorial, tips or tricks to use it in Android app ?

Thanks in advance.

**Comment by HoangTheBoss** [comment]
Probably no. Unless you wanted to set your phone on fire, but still no.

**Comment by mnicnc404** [comment]
Theoretically, yes, there can be light weight model that works on mobile device, but it may consume a lot of electricity of your device and make your device burn your hand, and the model performance might be not as satisfying as the original model. Most importantly, we're sorry that we don't have extra time and energy to write an Android app version of this repo.
